name-template: v$NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION
categories:
  - title: '🚀 Added'
    labels:
      - 'new_feature'
  - title: '📦 Changed'
    label:
      - 'enhancement'
  - title: '🐛 Deprecated'
    label:
      - 'deprecate'
  - title: '🚮 Removed'
    label:
      - 'remove'
  - title: '🔐 Security'
    label:
      - 'security'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR '
template: |
  ## Changelog

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
