class PredefinedActions:
    VERSION = "ONEBUILD_VERSION"
    HELP = "ONEBUILD_HELP"
    LIST = "ONEBUILD_LIST"
    LIST_RAW = "ONEBUILD_LIST_RAW"
    INIT = "ONEBUILD_INIT"
    PERFORM = "ONEBUILD_PERFROM"
