name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      env:
        GO111MODULE: on
      run: go build -v .
    
    - name: Test
      env:
        GO111MODULE: on
      run: go test -v -cover github.com/gopinath-langote/1build/testing -run .
