stages:
  - build
  - test

variables:
  GO_VERSION: "1.22"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go/pkg/mod"

before_script:
  - go version

build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go mod download
    - go build -v ./...
  artifacts:
    paths:
      - 1build
    expire_in: 1 hour

test:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - go test -v -cover ./...