stages:
  - build
  - test

variables:
  GO_VERSION: "1.22"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go/pkg/mod"

default:
  image: golang:${GO_VERSION}
  before_script:
    - go version
    - go mod download

build:
  stage: build
  script:
    - go build -v .
  artifacts:
    paths:
      - 1build
    expire_in: 1 hour

test:
  stage: test
  script:
    - go test -v -cover github.com/gopinath-langote/1build/testing -run .